# -*- coding: utf-8 -*-
# Arriaga Sanchez Genesis, Bajaña Tarira Jenniffer, Landazuri Barcia Liliana,
# Mieles Piloso Andrews, Vera Saltos Jimmy
################################################################################
## Form generated from reading UI file 'vtn_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)

class Ui_vtn_principal(object):
    def setupUi(self, vtn_principal):
        if not vtn_principal.objectName():
            vtn_principal.setObjectName(u"vtn_principal")
        vtn_principal.resize(324, 462)
        self.centralwidget = QWidget(vtn_principal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_nombre = QLabel(self.centralwidget)
        self.lbl_nombre.setObjectName(u"lbl_nombre")
        self.lbl_nombre.setGeometry(QRect(30, 40, 51, 21))
        font = QFont()
        font.setFamilies([u"Tw Cen MT Condensed Extra Bold"])
        font.setUnderline(True)
        self.lbl_nombre.setFont(font)
        self.txt_nombre = QLineEdit(self.centralwidget)
        self.txt_nombre.setObjectName(u"txt_nombre")
        self.txt_nombre.setGeometry(QRect(80, 40, 121, 31))
        font1 = QFont()
        font1.setFamilies([u"MV Boli"])
        self.txt_nombre.setFont(font1)
        self.txt_nombre.setMaxLength(50)
        self.btn_grabar = QPushButton(self.centralwidget)
        self.btn_grabar.setObjectName(u"btn_grabar")
        self.btn_grabar.setGeometry(QRect(120, 390, 75, 23))
        font2 = QFont()
        font2.setFamilies([u"Bahnschrift Light SemiCondensed"])
        self.btn_grabar.setFont(font2)
        self.lbl_apellido = QLabel(self.centralwidget)
        self.lbl_apellido.setObjectName(u"lbl_apellido")
        self.lbl_apellido.setGeometry(QRect(30, 80, 51, 21))
        font3 = QFont()
        font3.setFamilies([u"Tw Cen MT Condensed Extra Bold"])
        font3.setPointSize(8)
        font3.setUnderline(True)
        self.lbl_apellido.setFont(font3)
        self.txt_apellido = QLineEdit(self.centralwidget)
        self.txt_apellido.setObjectName(u"txt_apellido")
        self.txt_apellido.setGeometry(QRect(80, 80, 121, 31))
        self.txt_apellido.setFont(font1)
        self.txt_apellido.setMaxLength(50)
        self.cb_tipo_persona = QComboBox(self.centralwidget)
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.setObjectName(u"cb_tipo_persona")
        self.cb_tipo_persona.setGeometry(QRect(80, 10, 121, 22))
        self.cb_tipo_persona.setFont(font2)
        self.lbl_tipo_persona = QLabel(self.centralwidget)
        self.lbl_tipo_persona.setObjectName(u"lbl_tipo_persona")
        self.lbl_tipo_persona.setGeometry(QRect(30, 10, 51, 21))
        self.lbl_tipo_persona.setFont(font)
        self.lbl_cedula = QLabel(self.centralwidget)
        self.lbl_cedula.setObjectName(u"lbl_cedula")
        self.lbl_cedula.setGeometry(QRect(30, 120, 51, 21))
        self.lbl_cedula.setFont(font)
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(80, 120, 121, 31))
        self.txt_cedula.setFont(font1)
        self.txt_cedula.setMaxLength(10)
        self.lbl_email = QLabel(self.centralwidget)
        self.lbl_email.setObjectName(u"lbl_email")
        self.lbl_email.setGeometry(QRect(30, 160, 51, 21))
        self.lbl_email.setFont(font)
        self.txt_email = QLineEdit(self.centralwidget)
        self.txt_email.setObjectName(u"txt_email")
        self.txt_email.setGeometry(QRect(80, 160, 121, 31))
        self.txt_email.setFont(font1)
        self.txt_email.setMaxLength(100)
        self.btn_buscar_cedula = QPushButton(self.centralwidget)
        self.btn_buscar_cedula.setObjectName(u"btn_buscar_cedula")
        self.btn_buscar_cedula.setGeometry(QRect(210, 120, 101, 30))
        self.btn_buscar_cedula.setFont(font2)
        self.lbl_estatura = QLabel(self.centralwidget)
        self.lbl_estatura.setObjectName(u"lbl_estatura")
        self.lbl_estatura.setGeometry(QRect(30, 330, 61, 21))
        self.lbl_estatura.setFont(font)
        self.sp_estatura = QSpinBox(self.centralwidget)
        self.sp_estatura.setObjectName(u"sp_estatura")
        self.sp_estatura.setGeometry(QRect(100, 330, 42, 22))
        self.sp_estatura.setMaximum(300)
        self.btn_estatura = QPushButton(self.centralwidget)
        self.btn_estatura.setObjectName(u"btn_estatura")
        self.btn_estatura.setGeometry(QRect(150, 330, 81, 23))
        self.btn_estatura.setFont(font2)
        self.lbl_peso = QLabel(self.centralwidget)
        self.lbl_peso.setObjectName(u"lbl_peso")
        self.lbl_peso.setGeometry(QRect(30, 360, 61, 21))
        self.lbl_peso.setFont(font)
        self.sp_peso = QSpinBox(self.centralwidget)
        self.sp_peso.setObjectName(u"sp_peso")
        self.sp_peso.setGeometry(QRect(100, 360, 42, 22))
        self.sp_peso.setMaximum(90)
        self.lbl_edad = QLabel(self.centralwidget)
        self.lbl_edad.setObjectName(u"lbl_edad")
        self.lbl_edad.setGeometry(QRect(30, 300, 61, 21))
        self.lbl_edad.setFont(font)
        self.sp_edad = QSpinBox(self.centralwidget)
        self.sp_edad.setObjectName(u"sp_edad")
        self.sp_edad.setGeometry(QRect(100, 300, 42, 22))
        self.sp_edad.setMaximum(100)
        self.lbl_edad_2 = QLabel(self.centralwidget)
        self.lbl_edad_2.setObjectName(u"lbl_edad_2")
        self.lbl_edad_2.setGeometry(QRect(30, 270, 111, 21))
        self.lbl_edad_2.setFont(font)
        self.btn_edad = QPushButton(self.centralwidget)
        self.btn_edad.setObjectName(u"btn_edad")
        self.btn_edad.setGeometry(QRect(150, 300, 81, 23))
        self.btn_edad.setFont(font2)
        self.btn_peso = QPushButton(self.centralwidget)
        self.btn_peso.setObjectName(u"btn_peso")
        self.btn_peso.setGeometry(QRect(150, 360, 81, 23))
        self.btn_peso.setFont(font2)
        self.txt_carrera = QLineEdit(self.centralwidget)
        self.txt_carrera.setObjectName(u"txt_carrera")
        self.txt_carrera.setGeometry(QRect(80, 200, 121, 31))
        self.txt_carrera.setFont(font1)
        self.txt_carrera.setMaxLength(100)
        self.lbl_carrera = QLabel(self.centralwidget)
        self.lbl_carrera.setObjectName(u"lbl_carrera")
        self.lbl_carrera.setGeometry(QRect(30, 200, 51, 21))
        self.lbl_carrera.setFont(font)
        self.dae_fecha_nacimiento = QDateEdit(self.centralwidget)
        self.dae_fecha_nacimiento.setObjectName(u"dae_fecha_nacimiento")
        self.dae_fecha_nacimiento.setGeometry(QRect(130, 270, 110, 22))
        self.dae_fecha_nacimiento.setCalendarPopup(True)
        self.lbl_tipo_persona_2 = QLabel(self.centralwidget)
        self.lbl_tipo_persona_2.setObjectName(u"lbl_tipo_persona_2")
        self.lbl_tipo_persona_2.setGeometry(QRect(30, 240, 51, 21))
        self.lbl_tipo_persona_2.setFont(font)
        self.cb_tipo_habilitado = QComboBox(self.centralwidget)
        self.cb_tipo_habilitado.addItem("")
        self.cb_tipo_habilitado.addItem("")
        self.cb_tipo_habilitado.setObjectName(u"cb_tipo_habilitado")
        self.cb_tipo_habilitado.setGeometry(QRect(90, 240, 81, 22))
        self.cb_tipo_habilitado.setFont(font2)
        self.btn_cal_edad = QPushButton(self.centralwidget)
        self.btn_cal_edad.setObjectName(u"btn_cal_edad")
        self.btn_cal_edad.setGeometry(QRect(250, 270, 61, 20))
        self.btn_cal_edad.setFont(font2)
        vtn_principal.setCentralWidget(self.centralwidget)
        self.mnb_menu_principal = QMenuBar(vtn_principal)
        self.mnb_menu_principal.setObjectName(u"mnb_menu_principal")
        self.mnb_menu_principal.setGeometry(QRect(0, 0, 324, 21))
        vtn_principal.setMenuBar(self.mnb_menu_principal)
        self.stb_estado = QStatusBar(vtn_principal)
        self.stb_estado.setObjectName(u"stb_estado")
        vtn_principal.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_principal)

        QMetaObject.connectSlotsByName(vtn_principal)
    # setupUi

    def retranslateUi(self, vtn_principal):
        vtn_principal.setWindowTitle(QCoreApplication.translate("vtn_principal", u"Ingreso Persona", None))
        self.lbl_nombre.setText(QCoreApplication.translate("vtn_principal", u"Nombre:", None))
        self.btn_grabar.setText(QCoreApplication.translate("vtn_principal", u"Grabar", None))
        self.lbl_apellido.setText(QCoreApplication.translate("vtn_principal", u"Apellido:", None))
        self.cb_tipo_persona.setItemText(0, QCoreApplication.translate("vtn_principal", u"Docente", None))
        self.cb_tipo_persona.setItemText(1, QCoreApplication.translate("vtn_principal", u"Estudiante", None))

        self.lbl_tipo_persona.setText(QCoreApplication.translate("vtn_principal", u"Tipo:", None))
        self.lbl_cedula.setText(QCoreApplication.translate("vtn_principal", u"Cedula:", None))
        self.lbl_email.setText(QCoreApplication.translate("vtn_principal", u"Email:", None))
        self.btn_buscar_cedula.setText(QCoreApplication.translate("vtn_principal", u"Buscar por cedula", None))
        self.lbl_estatura.setText(QCoreApplication.translate("vtn_principal", u"Estatura(cm)l:", None))
        self.btn_estatura.setText(QCoreApplication.translate("vtn_principal", u"E.D. Estatura", None))
        self.lbl_peso.setText(QCoreApplication.translate("vtn_principal", u"Peso(kg):", None))
        self.lbl_edad.setText(QCoreApplication.translate("vtn_principal", u"Edad:", None))
        self.lbl_edad_2.setText(QCoreApplication.translate("vtn_principal", u"Fecha de Nacimiento:", None))
        self.btn_edad.setText(QCoreApplication.translate("vtn_principal", u"E.D. EDAD", None))
        self.btn_peso.setText(QCoreApplication.translate("vtn_principal", u"E.D. PESO", None))
        self.txt_carrera.setText("")
        self.lbl_carrera.setText(QCoreApplication.translate("vtn_principal", u"Carrera:", None))
        self.lbl_tipo_persona_2.setText(QCoreApplication.translate("vtn_principal", u"Habilitado:", None))
        self.cb_tipo_habilitado.setItemText(0, QCoreApplication.translate("vtn_principal", u"No", None))
        self.cb_tipo_habilitado.setItemText(1, QCoreApplication.translate("vtn_principal", u"Si", None))

        self.btn_cal_edad.setText(QCoreApplication.translate("vtn_principal", u"C.Edad", None))
    # retranslateUi

